ame: MLC Docker core action tests

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/test-mlc-podman.yml'
      - '**'
      - '!**.md'

jobs:
  test_mlc_docker_core:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.8"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        exclude:
          - os: windows-latest
          - os: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure git longpaths (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git config --system core.longpaths true

    - name: Uninstall docker and install podman
      run: |
        sudo apt remove -y docker.io docker-ce docker-ce-cli containerd.io docker-compose-plugin
        sudo apt purge -y docker.io docker-ce docker-ce-cli containerd.io docker-compose-plugin
        sudo rm -rf /var/lib/docker /var/lib/containerd
        sudo apt update
        sudo apt install -y podman
        podman --version

    - name: Install mlcflow from the pull request's source repository and branch
      run: |
        python -m pip install --upgrade pip
        python -m pip install --ignore-installed --verbose pip setuptools
        python -m pip install .
